package baseline;

public class GuessingGame {
    //Store number generated by random generation
    int randomNumberToGuess;

    public int getRandomNumberToGuess() {
        //used for junit testing
        return randomNumberToGuess;
    }

    public int setGuessNumber() {
        //prompt user for a guess and store it if it's a numeric entry
        return 0;
    }

    public void playGuessingGame() {
        //contains the loop for playing the game and an inner loop for guesses
        //also calls other functions needed
        //use counter to store amount of guesses
        int numberOfGuesses = 1;
        //use boolean to tell if the guess is too high or too low.
    }

    public int setGuessAgain() {
        //prompts for guess after getting it wrong
        return 0;
    }
}
